name: "Create draft release after tag"
on:
  push:
    tags: ["v*"]
permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Extract version"
        run: echo "IMAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: "Create release"
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          draft: true
          generate_release_notes: true
          body: |
            ## Docker image

            The service is available as a Docker image from the [GitHub Container Registry](https://github.com/element-hq/lk-jwt-service/pkgs/container/lk-jwt-service).

            ```
            docker pull ghcr.io/element-hq/lk-jwt-service:${{env.IMAGE_VERSION}}
            ```
